# Project: 根据数字判断星期
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = 根据数字判断星期.o
LINKOBJ  = 根据数字判断星期.o
LIBS     = -L"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/lib" -L"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/include" -I"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"D:/App/Dev-Cpp/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 根据数字判断星期.exe
CXXFLAGS = $(CXXINCS) -g3 -g3 -fexec-charset=UTF-8 -finput-charset=UTF-8
CFLAGS   = $(INCS) -g3 -g3 -fexec-charset=UTF-8 -finput-charset=UTF-8
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

根据数字判断星期.o: 根据数字判断星期.cpp
	$(CPP) -c 根据数字判断星期.cpp -o 根据数字判断星期.o $(CXXFLAGS)
